# Generated by Django 4.2.21 on 2025-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(error_messages={'unique': 'El correo electrónico ya se encuentra registrado'}, max_length=60, unique=True),
        ),
    ]
