# Generated by Django 4.2.21 on 2025-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_direccion_departamento_usuario_gerente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
