# Generated by Django 4.2.21 on 2025-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_persona_direccion_alter_persona_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='FechaDeNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
