# Generated by Django 4.2.21 on 2025-05-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_fechadenacimiento_persona_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='mail',
            new_name='email',
        ),
    ]
