# Generated by Django 4.2.21 on 2025-05-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_mail_persona_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
