version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: rentax
      POSTGRES_USER: rentax_user
      POSTGRES_PASSWORD: rentax_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=sup3rs3cr3t
      - DB_NAME=rentax
      - DB_USER=rentax_user
      - DB_PASSWORD=rentax_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
