import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="bg-gradient-to-r from-red-500 to-orange-500 text-black p-4 text-center">
       <Navigation/>
     
      </header>
        {children}
        <footer className="bg-gradient-to-r from-blue-500 to-green-500 text-black p-4 text-center">
          <p className="text-2xl font-bold">Thank you for visiting us</p>
        </footer>
      </body>
    </html>
  );
}
