# Generated by Django 4.2.21 on 2025-05-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_direccion_departamento_usuario_gerente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadDias', models.IntegerField()),
                ('realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
