# Generated by Django 4.2.21 on 2025-05-10 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_localidad_propiedad_localidad'),
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='realizado',
            new_name='inquilino',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='perteneceAPropiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad'),
        ),
    ]
