# Generated by Django 4.2.21 on 2025-05-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='cantidadDias',
        ),
    ]
