# Generated by Django 4.2.21 on 2025-05-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_Propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='propiedades.tipopropiedad'),
        ),
    ]
