# Generated by Django 4.2.21 on 2025-05-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaSinReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedades.politica_de_cancelacion')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaConReembolsoParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedades.politica_de_cancelacion')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaConReembolsoCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedades.politica_de_cancelacion')),
            ],
        ),
    ]
