# Generated by Django 4.2.21 on 2025-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipoPropiedad',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
