# Generated by Django 4.2.21 on 2025-05-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_tipopropiedad_propiedad_tipo_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politica_De_Cancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_Propiedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.tipopropiedad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='politica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.politica_de_cancelacion'),
        ),
    ]
