# Generated by Django 4.2.21 on 2025-05-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_politica_de_cancelacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cochera',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedades.propiedad')),
                ('cupo_de_autos', models.IntegerField()),
            ],
            bases=('propiedades.propiedad',),
        ),
        migrations.CreateModel(
            name='LocalComercial',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedades.propiedad')),
                ('caracteristicas', models.TextField(max_length=200)),
            ],
            bases=('propiedades.propiedad',),
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('propiedad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedades.propiedad')),
                ('caracteristicas', models.TextField(max_length=200)),
            ],
            bases=('propiedades.propiedad',),
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_Propiedad',
        ),
        migrations.DeleteModel(
            name='TipoPropiedad',
        ),
    ]
