# Generated by Django 4.2.21 on 2025-05-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedad_calle_propiedad_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='numero',
            field=models.IntegerField(default=-1),
        ),
    ]
