# Generated by Django 4.2.21 on 2025-05-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_localidad_propiedad_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='baños',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cantidadDiasMinimo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='huespedes',
            field=models.IntegerField(null=True),
        ),
    ]
