# Generated by Django 4.2.21 on 2025-05-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_direccion_departamento_usuario_gerente_and_more'),
        ('propiedades', '0006_propiedad_baños_propiedad_cantidaddiasminimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.direccion'),
        ),
    ]
