# Generated by Django 4.2.21 on 2025-05-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_tipopropiedad'),
        ('propiedades', '0006_alter_propiedad_numero'),
    ]

    operations = [
    ]
