# Generated by Django 4.2.21 on 2025-05-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_alter_propiedad_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='habitaciones',
            new_name='ambientes',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='baños',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='cantidadDiasMinimo',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='huespedes',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='baños',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='cantidadDiasMinimo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='huespedes',
            field=models.IntegerField(null=True),
        ),
    ]
