# Generated by Django 4.2.21 on 2025-05-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_merge_20250522_1701'),
        ('propiedades', '0007_merge_20250522_1728'),
    ]

    operations = [
    ]
