# Generated by Django 4.2.21 on 2025-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_merge_20250523_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='cantidadDiasMinimo',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cantidadDiasMinimo',
            field=models.IntegerField(null=True),
        ),
    ]
