# Generated by Django 4.2.21 on 2025-05-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_merge_20250523_1516'),
        ('propiedades', '0009_remove_vivienda_cantidaddiasminimo_and_more'),
    ]

    operations = [
    ]
